# Generated by Django 4.2.7 on 2025-11-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deck_name', models.CharField(max_length=200, verbose_name='Название колоды')),
                ('file_path', models.FilePathField(path='temp_files/', verbose_name='Путь к файлу')),
                ('cards_count', models.IntegerField(verbose_name='Количество карточек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_decks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сгенерированная колода',
                'verbose_name_plural': 'Сгенерированные колоды',
                'ordering': ['-created_at'],
            },
        ),
    ]
