# Generated by Django 4.2.7 on 2025-11-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddeck',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='Путь к файлу'),
        ),
    ]
