# Generated by Django 4.2.7 on 2025-11-19 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_alter_generateddeck_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('image', 'Генерация изображений'), ('audio', 'Генерация аудио'), ('word_analysis', 'Анализ смешанных языков'), ('translation', 'Перевод слов'), ('deck_name', 'Генерация названия колоды'), ('part_of_speech', 'Определение части речи'), ('category', 'Определение категории')], max_length=50, verbose_name='Тип промпта')),
                ('custom_prompt', models.TextField(verbose_name='Пользовательский промпт')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательский промпт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Промпт пользователя',
                'verbose_name_plural': 'Промпты пользователей',
                'ordering': ['prompt_type'],
                'unique_together': {('user', 'prompt_type')},
            },
        ),
    ]
