# Generated by Django 4.2.7 on 2025-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_userprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeechCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово')),
                ('language', models.CharField(max_length=2, verbose_name='Язык')),
                ('part_of_speech', models.CharField(max_length=50, verbose_name='Часть речи')),
                ('article', models.CharField(blank=True, max_length=10, null=True, verbose_name='Артикль (для немецкого)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кэш части речи',
                'verbose_name_plural': 'Кэш частей речи',
                'indexes': [models.Index(fields=['word', 'language'], name='cards_parto_word_cb9a96_idx')],
                'unique_together': {('word', 'language')},
            },
        ),
    ]
