# Generated by Django 4.2.7 on 2025-12-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0001_initial'),
        ('cards', '0004_partofspeechcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название колоды')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='deck_covers/', verbose_name='Обложка колоды')),
                ('target_lang', models.CharField(choices=[('pt', 'Португальский'), ('de', 'Немецкий')], max_length=2, verbose_name='Язык изучения')),
                ('source_lang', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Português'), ('de', 'Deutsch')], default='ru', max_length=2, verbose_name='Родной язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('words', models.ManyToManyField(blank=True, related_name='decks', to='words.word', verbose_name='Слова')),
            ],
            options={
                'verbose_name': 'Колода',
                'verbose_name_plural': 'Колоды',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='cards_deck_user_id_28f90a_idx')],
            },
        ),
    ]
