# Generated by Django 4.2.7 on 2025-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_token_tokentransaction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generateddeck',
            index=models.Index(fields=['user', 'created_at'], name='cards_gener_user_id_4f9b71_idx'),
        ),
        migrations.AddIndex(
            model_name='userprompt',
            index=models.Index(fields=['user', 'prompt_type'], name='cards_userp_user_id_561e92_idx'),
        ),
    ]
