# Generated by Django 4.2.7 on 2025-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_generateddeck_cards_gener_user_id_4f9b71_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='source_lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Português'), ('de', 'Deutsch'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano')], default='ru', max_length=2, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='target_lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Португальский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('fr', 'Французский'), ('it', 'Итальянский')], max_length=2, verbose_name='Язык изучения'),
        ),
    ]
