# Generated by Django 4.2.7 on 2026-01-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_remove_category_unique_category_name_per_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0008_alter_deck_source_lang_alter_deck_target_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('normal', 'Обычная'), ('inverted', 'Инвертированная'), ('empty', 'Пустая'), ('cloze', 'С пропуском')], default='normal', max_length=20, verbose_name='Тип карточки')),
                ('cloze_sentence', models.TextField(blank=True, default='', help_text='Полное предложение без пропуска', verbose_name='Предложение для cloze')),
                ('cloze_word_index', models.IntegerField(default=0, help_text='Позиция слова в предложении (0-based)', verbose_name='Индекс пропущенного слова')),
                ('ease_factor', models.FloatField(default=2.5, help_text='Коэффициент лёгкости (минимум 1.3)', verbose_name='Ease Factor')),
                ('interval', models.IntegerField(default=0, help_text='Текущий интервал повторения', verbose_name='Интервал (дни)')),
                ('repetitions', models.IntegerField(default=0, help_text='Количество успешных повторений подряд', verbose_name='Успешные повторения')),
                ('lapses', models.IntegerField(default=0, help_text='Общее количество нажатий "Снова"', verbose_name='Общие провалы')),
                ('consecutive_lapses', models.IntegerField(default=0, help_text='Провалы подряд (4 → режим Изучения)', verbose_name='Провалы подряд')),
                ('next_review', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Следующий показ')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='Последний показ')),
                ('learning_step', models.IntegerField(default=0, help_text='Текущий шаг: 0=2мин, 1=10мин (настраивается в UserTrainingSettings)', verbose_name='Шаг обучения')),
                ('is_in_learning_mode', models.BooleanField(default=True, help_text='True = ещё не прошёл Learning Mode', verbose_name='В режиме изучения')),
                ('is_auxiliary', models.BooleanField(default=False, help_text='True = empty/cloze, может "сгореть"', verbose_name='Вспомогательная')),
                ('is_suspended', models.BooleanField(db_index=True, default=False, verbose_name='Приостановлена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='words.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['next_review', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_suspended', 'next_review'], name='cards_card_user_id_1617bf_idx'), models.Index(fields=['user', 'is_in_learning_mode'], name='cards_card_user_id_3f48bc_idx'), models.Index(fields=['word', 'card_type'], name='cards_card_word_id_fee223_idx')],
                'unique_together': {('word', 'card_type', 'cloze_sentence')},
            },
        ),
    ]
