# Generated by Django 4.2.7 on 2026-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='source_lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Português'), ('de', 'Deutsch'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('tr', 'Türkçe')], default='ru', max_length=2, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='target_lang',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Португальский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('fr', 'Французский'), ('it', 'Итальянский'), ('tr', 'Турецкий')], max_length=2, verbose_name='Язык изучения'),
        ),
    ]
