# Generated by Django 4.2.7 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_deck_source_lang_alter_deck_target_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_learning_active',
            field=models.BooleanField(default=False, help_text='True = карточки из колоды попадают в общую тренировку', verbose_name='Активна для тренировки'),
        ),
    ]
