# Generated by Django 4.2.17 on 2026-03-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literary_context', '0002_add_embedding_field'),
        ('cards', '0011_deck_is_learning_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='literary_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='literary_context.literarysource', verbose_name='Литературный источник'),
        ),
    ]
