# Generated by Django 4.2.17 on 2026-03-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_deck_literary_source_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='source_lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], default='ru', max_length=2, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='target_lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], max_length=2, verbose_name='Язык изучения'),
        ),
    ]
