# Generated by Django 4.2.7 on 2025-12-15 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiSyncUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_path', models.CharField(max_length=500, verbose_name='Путь к базе данных коллекции')),
                ('host_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ хоста')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последней синхронизации')),
                ('client_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версия клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anki_sync', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Синхронизация Anki',
                'verbose_name_plural': 'Синхронизации Anki',
            },
        ),
        migrations.CreateModel(
            name='AnkiSyncMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sync_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='anki_sync.ankisyncuser', verbose_name='Пользователь синхронизации')),
            ],
            options={
                'verbose_name': 'Медиафайл синхронизации',
                'verbose_name_plural': 'Медиафайлы синхронизации',
                'unique_together': {('sync_user', 'file_name')},
            },
        ),
    ]
