# Generated by Django 4.2.7 on 2025-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_language',
            field=models.CharField(choices=[('pt', 'Português'), ('de', 'Deutsch')], default='pt', max_length=2, verbose_name='Язык изучения'),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Português'), ('de', 'Deutsch')], default='ru', max_length=2, verbose_name='Родной язык'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=10, verbose_name='Тема интерфейса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
