# Generated by Django 4.2.7 on 2025-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_learning_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('simple', 'Простой'), ('advanced', 'Расширенный')], default='advanced', max_length=10, verbose_name='Режим работы'),
        ),
    ]
