# Generated by Django 4.2.7 on 2025-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_provider',
            field=models.CharField(choices=[('openai', 'OpenAI DALL-E 3'), ('gemini', 'Google Gemini (Nano Banana)')], default='openai', max_length=20, verbose_name='Провайдер генерации изображений'),
        ),
    ]
