# Generated by Django 4.2.7 on 2025-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash-image', 'Gemini Flash (быстрая, 0.5 токена)'), ('nano-banana-pro-preview', 'Nano Banana Pro (новая, 1 токен)')], default='gemini-2.5-flash-image', max_length=50, verbose_name='Модель Gemini для генерации изображений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_provider',
            field=models.CharField(choices=[('openai', 'OpenAI DALL-E 3'), ('gemini', 'Google Gemini')], default='openai', max_length=20, verbose_name='Провайдер генерации изображений'),
        ),
    ]
