# Generated by Django 4.2.7 on 2025-12-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gemini_model_alter_user_image_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learning_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], default='de', max_length=2, verbose_name='Язык изучения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=2, verbose_name='Родной язык'),
        ),
    ]
