# Generated by Django 4.2.7 on 2025-12-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_expand_language_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=2, verbose_name='Предпочитаемый язык'),
        ),
    ]
