# Generated by Django 4.2.7 on 2025-12-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_expand_preferred_language_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_provider',
            field=models.CharField(choices=[('openai', 'OpenAI TTS'), ('gtts', 'Google TTS (gTTS)')], default='openai', max_length=20, verbose_name='Провайдер генерации аудио'),
        ),
    ]
