# Generated by Django 4.2.7 on 2026-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_audio_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learning_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], default='de', max_length=2, verbose_name='Язык изучения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], default='en', max_length=2, verbose_name='Родной язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], default='en', max_length=2, verbose_name='Предпочитаемый язык'),
        ),
    ]
