# Generated by Django 4.2.7 on 2026-03-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literary_context', '0002_add_embedding_field'),
        ('users', '0009_alter_user_learning_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_literary_source',
            field=models.ForeignKey(blank=True, help_text='Если выбран, медиа слов будут из литературного источника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='literary_context.literarysource', verbose_name='Активный литературный контекст'),
        ),
    ]
