# Generated by Django 4.2.17 on 2026-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_active_literary_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_style',
            field=models.CharField(choices=[('minimalistic', 'Минималистичный'), ('balanced', 'Сбалансированный'), ('creative', 'Креативный')], default='balanced', max_length=20, verbose_name='Стиль генерации изображений'),
        ),
    ]
