# Generated by Django 4.2.7 on 2026-03-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0011_category_is_learning_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryContextSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_match_min_score', models.FloatField(default=0.7, help_text='Minimum cosine similarity for semantic search (0.0-1.0)')),
                ('llm_match_enabled', models.BooleanField(default=True, help_text='Enable LLM-based matching as Tier C fallback')),
                ('image_prompt_template', models.TextField(default='Illustration of a scene from a literary work: {scene_description}. Style: classic book illustration, warm tones, detailed. NO text, letters, words, signs, or symbols anywhere in the image.', help_text='Template for scene image generation. Variables: {scene_description}')),
                ('hint_prompt_template', models.TextField(default="Based on this literary passage:\n{fragment_content}\n\nCreate a short hint (1-2 sentences) for the word '{word}' that references this scene. Do NOT use the word itself or its translation '{translation}'. Write the hint in {language_name}.", help_text='Template for hint generation. Variables: {fragment_content}, {word}, {translation}, {language_name}')),
                ('sentence_extraction_prompt', models.TextField(default="From the following literary passage, extract sentences that contain the word '{word}' (or its grammatical forms). Return only the sentences, one per line. If no sentences contain the word, return the most relevant sentence from the passage.\n\nPassage:\n{fragment_content}", help_text='Template for sentence extraction. Variables: {word}, {fragment_content}')),
                ('keyword_extraction_prompt', models.TextField(default='Extract key words from this text fragment. Return as a JSON array of strings. Include nouns, verbs, adjectives that describe the main objects, actions, and qualities in the scene. Return 5-15 words.\n\nText:\n{fragment_content}', help_text='Template for keyword extraction during indexing. Variables: {fragment_content}')),
                ('scene_description_prompt', models.TextField(default='Describe the visual scene from this literary passage in English. Focus on what can be SEEN: characters, their actions, surroundings, mood, lighting, colors. Keep it to 2-3 sentences. Also extract: 1) character names (Latin script), 2) scene mood.\n\nReturn as JSON: {{"description": "...", "characters": [...], "mood": "..."}}\n\nPassage:\n{fragment_content}', help_text='Template for scene description generation. Variables: {fragment_content}')),
                ('keyword_extraction_model', models.CharField(default='gpt-4o-mini', help_text='Model for keyword extraction during indexing', max_length=50)),
                ('scene_description_model', models.CharField(default='gpt-4o-mini', help_text='Model for scene description generation', max_length=50)),
                ('hint_generation_model', models.CharField(default='gpt-4o-mini', help_text='Model for hint text generation', max_length=50)),
                ('matching_model', models.CharField(default='gpt-4o', help_text='Model for Tier C LLM matching (complex cases)', max_length=50)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='Model for generating embeddings', max_length=50)),
                ('embedding_dimensions', models.IntegerField(default=1536, help_text='Embedding vector dimensions')),
                ('scene_image_cost', models.IntegerField(default=4, help_text='Token cost for scene image (internal units, 2=1 real token)')),
                ('hint_generation_cost', models.IntegerField(default=2, help_text='Token cost for hint text generation')),
                ('audio_generation_cost', models.IntegerField(default=2, help_text='Token cost for audio via ElevenLabs')),
                ('llm_matching_cost', models.IntegerField(default=2, help_text='Token cost for Tier C LLM matching')),
                ('default_fragment_size', models.IntegerField(default=500, help_text='Target fragment size in characters')),
                ('fragment_overlap', models.IntegerField(default=50, help_text='Overlap between fragments in characters')),
                ('hint_temperature', models.FloatField(default=0.8)),
                ('keyword_temperature', models.FloatField(default=0.3)),
                ('scene_description_temperature', models.FloatField(default=0.5)),
                ('matching_temperature', models.FloatField(default=0.2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Literary Context Settings',
                'verbose_name_plural': 'Literary Context Settings',
            },
        ),
        migrations.CreateModel(
            name='LiterarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='literary_sources/')),
                ('source_language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], max_length=2)),
                ('available_languages', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Literary Source',
                'verbose_name_plural': 'Literary Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SceneAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_slug', models.SlugField(max_length=100)),
                ('fragment_index', models.IntegerField()),
                ('scene_description', models.TextField(blank=True, default='', help_text='AI-generated scene description in English (for image prompt)')),
                ('characters', models.JSONField(default=list, help_text='Characters in the scene, Latin script: ["Ochumelov", "Khryukin"]')),
                ('mood', models.CharField(choices=[('comedic', 'Comedic'), ('dramatic', 'Dramatic'), ('calm', 'Calm'), ('tense', 'Tense'), ('melancholic', 'Melancholic'), ('joyful', 'Joyful'), ('mysterious', 'Mysterious'), ('romantic', 'Romantic'), ('dark', 'Dark'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='literary_scenes/')),
                ('image_prompt', models.TextField(blank=True, default='', help_text='The actual prompt sent to DALL-E/Gemini')),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_anchors', to='literary_context.literarysource')),
            ],
            options={
                'verbose_name': 'Scene Anchor',
                'verbose_name_plural': 'Scene Anchors',
                'ordering': ['source', 'text_slug', 'fragment_index'],
                'unique_together': {('source', 'text_slug', 'fragment_index')},
            },
        ),
        migrations.CreateModel(
            name='LiteraryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], max_length=2)),
                ('full_text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='literary_context.literarysource')),
            ],
            options={
                'verbose_name': 'Literary Text',
                'verbose_name_plural': 'Literary Texts',
                'ordering': ['source', 'slug', 'language'],
                'unique_together': {('source', 'slug', 'language')},
            },
        ),
        migrations.CreateModel(
            name='LiteraryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The actual text passage in this language')),
                ('key_words', models.JSONField(default=list, help_text='Key words in this language: ["Hund", "Platz", "Menge"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='literary_context.sceneanchor')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='literary_context.literarytext')),
            ],
            options={
                'verbose_name': 'Literary Fragment',
                'verbose_name_plural': 'Literary Fragments',
                'ordering': ['anchor__fragment_index'],
                'unique_together': {('anchor', 'text')},
            },
        ),
        migrations.CreateModel(
            name='WordContextMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField(blank=True, default='')),
                ('hint_audio', models.FileField(blank=True, null=True, upload_to='literary_hints/')),
                ('sentences', models.JSONField(default=list, help_text='Sentences from the literary work: [{"text": "...", "source": "chekhov"}]')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='literary_audio/')),
                ('is_fallback', models.BooleanField(default=False, help_text='True if no matching fragment found in the literary source')),
                ('match_method', models.CharField(blank=True, default='', help_text='How the word was matched: keyword, semantic, llm, fallback', max_length=20)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_media', to='literary_context.sceneanchor')),
                ('fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_media', to='literary_context.literaryfragment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_media', to='literary_context.literarysource')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_media', to='words.word')),
            ],
            options={
                'verbose_name': 'Word Context Media',
                'verbose_name_plural': 'Word Context Media',
                'indexes': [models.Index(fields=['word', 'source'], name='literary_co_word_id_b0f837_idx'), models.Index(fields=['source', 'anchor'], name='literary_co_source__cd5173_idx')],
                'unique_together': {('word', 'source')},
            },
        ),
    ]
