# Generated by Django 4.2.7 on 2026-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literary_context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaryfragment',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Embedding vector as JSON list. Use pgvector VectorField in production.', null=True),
        ),
    ]
