# Generated by Django 4.2.17 on 2026-03-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literary_context', '0002_add_embedding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='literarytext',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Order within source for TOC'),
        ),
        migrations.AddField(
            model_name='literarytext',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Approximate word count'),
        ),
        migrations.AddField(
            model_name='literarytext',
            name='year',
            field=models.IntegerField(blank=True, help_text='Year of original publication', null=True),
        ),
    ]
