# Generated by Django 4.2.7 on 2026-01-11 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('young', 'До 18 лет'), ('adult', '18-50 лет'), ('senior', '50+ лет')], default='adult', help_text='Влияет на начальные параметры', max_length=20, verbose_name='Возрастная группа')),
                ('starting_ease', models.FloatField(default=2.5, help_text='EF для новых карточек', verbose_name='Начальный Ease Factor')),
                ('min_ease_factor', models.FloatField(default=1.3, help_text='Нижний предел EF (не может быть меньше)', verbose_name='Минимальный Ease Factor')),
                ('again_ef_delta', models.FloatField(default=-0.2, help_text='Изменение EF при нажатии "Снова"', verbose_name='Дельта EF при "Снова"')),
                ('hard_ef_delta', models.FloatField(default=-0.15, help_text='Изменение EF при нажатии "Трудно"', verbose_name='Дельта EF при "Трудно"')),
                ('good_ef_delta', models.FloatField(default=0.0, help_text='Изменение EF при нажатии "Хорошо"', verbose_name='Дельта EF при "Хорошо"')),
                ('easy_ef_delta', models.FloatField(default=0.15, help_text='Изменение EF при нажатии "Легко"', verbose_name='Дельта EF при "Легко"')),
                ('interval_modifier', models.FloatField(default=1.0, help_text='Умножается на все интервалы (для калибровки)', verbose_name='Глобальный модификатор интервалов')),
                ('hard_interval_modifier', models.FloatField(default=1.2, help_text='Умножается на интервал при "Трудно"', verbose_name='Модификатор для "Трудно"')),
                ('easy_bonus', models.FloatField(default=1.3, help_text='Умножается на интервал при "Легко"', verbose_name='Бонус для "Легко"')),
                ('learning_steps', models.JSONField(default=list, help_text='Интервалы внутри сессии: [2, 10] означает 2 мин, затем 10 мин', verbose_name='Шаги обучения (минуты)')),
                ('graduating_interval', models.IntegerField(default=1, help_text='Интервал после прохождения всех шагов обучения', verbose_name='Интервал выпуска (дни)')),
                ('easy_interval', models.IntegerField(default=4, help_text='Интервал если сразу нажали "Легко" в режиме изучения', verbose_name='Интервал при "Легко" (дни)')),
                ('default_session_duration', models.IntegerField(default=20, help_text='Стандартное время тренировки', verbose_name='Длительность сессии по умолчанию (минуты)')),
                ('lapse_threshold', models.IntegerField(default=4, help_text='Количество провалов подряд → режим Изучения', verbose_name='Порог провалов')),
                ('stability_threshold', models.IntegerField(default=60, help_text='Интервал карточки >= этого значения → удаление вспомогательных', verbose_name='Порог стабильности (дни)')),
                ('calibration_interval', models.IntegerField(default=50, help_text='Калибровка каждые N ответов', verbose_name='Интервал калибровки')),
                ('target_retention', models.FloatField(default=0.9, help_text='Целевой процент успешных ответов для калибровки (0.90 = 90%)', verbose_name='Целевой процент успеха')),
                ('total_reviews', models.IntegerField(default=0, help_text='Общее количество ответов пользователя', verbose_name='Всего ответов')),
                ('successful_reviews', models.IntegerField(default=0, help_text='Количество успешных ответов (Good/Easy)', verbose_name='Успешных ответов')),
                ('last_calibration_at', models.IntegerField(default=0, help_text='Номер ответа, на котором была последняя калибровка', verbose_name='Последняя калибровка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки тренировки',
                'verbose_name_plural': 'Настройки тренировки',
                'ordering': ['-created_at'],
            },
        ),
    ]
