# Generated by Django 4.2.7 on 2026-02-08 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_notifications_enabled', models.BooleanField(default=True, help_text='Показывать уведомления, когда приложение открыто', verbose_name='Уведомления в браузере')),
                ('notification_frequency', models.CharField(choices=[('aggressive', 'Агрессивный (каждые 4 часа)'), ('normal', 'Обычный (2 раза в день)'), ('minimal', 'Минимальный (1 раз в день)'), ('off', 'Выключены')], default='normal', max_length=20, verbose_name='Частота уведомлений')),
                ('notify_cards_due', models.BooleanField(default=True, help_text='Уведомлять когда есть карточки для повторения', verbose_name='Карточки готовы к повторению')),
                ('notify_streak_warning', models.BooleanField(default=True, help_text='Предупреждать о потере стрика', verbose_name='Стрик в опасности')),
                ('notify_daily_goal', models.BooleanField(default=True, help_text='Напоминать о дневной цели', verbose_name='Дневная цель')),
                ('cards_due_threshold', models.IntegerField(default=5, help_text='Уведомлять только если карточек >= этого числа', verbose_name='Минимум карточек для уведомления')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(default='08:00', verbose_name='Конец тихих часов')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
