# Generated by Django 4.2.7 on 2026-02-08 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_add_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Конец тихих часов'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Начало тихих часов'),
        ),
    ]
