# Generated by Django 4.2.7 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_notificationsettings_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingsettings',
            name='include_orphan_words',
            field=models.BooleanField(default=False, help_text='Слова, не привязанные ни к одной колоде, попадают в общую тренировку', verbose_name='Включать слова без колоды в тренировку'),
        ),
    ]
