# Generated by Django 4.2.7 on 2026-02-08 13:48

from django.db import migrations


def activate_existing_data(apps, schema_editor):
    """
    Активирует все существующие колоды и категории, у которых есть слова с карточками.
    Это нужно чтобы поведение не изменилось для текущих пользователей --
    их карточки по-прежнему должны попадать в тренировку.
    Также включает include_orphan_words для всех существующих пользователей.
    """
    Deck = apps.get_model('cards', 'Deck')
    Category = apps.get_model('words', 'Category')
    UserTrainingSettings = apps.get_model('training', 'UserTrainingSettings')
    
    # Активируем все колоды, у которых есть слова
    decks_with_words = Deck.objects.filter(words__isnull=False).distinct()
    decks_with_words.update(is_learning_active=True)
    
    # Активируем все категории, у которых есть слова
    categories_with_words = Category.objects.filter(words__isnull=False).distinct()
    categories_with_words.update(is_learning_active=True)
    
    # Включаем orphan words для всех существующих настроек тренировки
    UserTrainingSettings.objects.all().update(include_orphan_words=True)


def deactivate_all(apps, schema_editor):
    """Обратная миграция: деактивировать всё"""
    Deck = apps.get_model('cards', 'Deck')
    Category = apps.get_model('words', 'Category')
    UserTrainingSettings = apps.get_model('training', 'UserTrainingSettings')
    
    Deck.objects.all().update(is_learning_active=False)
    Category.objects.all().update(is_learning_active=False)
    UserTrainingSettings.objects.all().update(include_orphan_words=False)


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_usertrainingsettings_include_orphan_words'),
        ('cards', '0011_deck_is_learning_active'),
        ('words', '0011_category_is_learning_active'),
    ]

    operations = [
        migrations.RunPython(activate_existing_data, deactivate_all),
    ]
