# Generated by Django 4.2.7 on 2025-11-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=200, verbose_name='Исходное слово')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('language', models.CharField(choices=[('pt', 'Португальский'), ('de', 'Немецкий')], max_length=2, verbose_name='Язык')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Аудиофайл')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'language'], name='words_word_user_id_bde801_idx'), models.Index(fields=['user', 'original_word'], name='words_word_user_id_0d469a_idx')],
                'unique_together': {('user', 'original_word', 'language')},
            },
        ),
    ]
