# Generated by Django 4.2.7 on 2025-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Португальский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('fr', 'Французский'), ('it', 'Итальянский')], max_length=2, verbose_name='Язык'),
        ),
    ]
