# Generated by Django 4.2.7 on 2026-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='card_type',
            field=models.CharField(choices=[('normal', 'Обычная карточка'), ('inverted', 'Инвертированная карточка'), ('empty', 'Пустая карточка')], default='normal', help_text='Тип карточки: обычная, инвертированная или пустая', max_length=10, verbose_name='Тип карточки'),
        ),
    ]
