# Generated by Django 4.2.7 on 2026-01-02 15:38

from django.db import migrations


def set_card_types_for_existing_words(apps, schema_editor):
    """
    Устанавливает правильные типы карточек для существующих слов:
    - Пустые карточки (original_word начинается с '_empty_') -> 'empty'
    - Остальные -> 'normal' (по умолчанию уже установлено, но обновим для ясности)
    """
    Word = apps.get_model('words', 'Word')
    
    # Обновляем пустые карточки
    empty_count = Word.objects.filter(original_word__startswith='_empty_').update(card_type='empty')
    
    # Убеждаемся, что все остальные имеют тип 'normal' (на случай если что-то пошло не так)
    normal_count = Word.objects.exclude(original_word__startswith='_empty_').exclude(card_type='inverted').update(card_type='normal')
    
    print(f"✅ Обновлено типов карточек: {empty_count} пустых, {normal_count} обычных")


def reverse_set_card_types(apps, schema_editor):
    """
    Обратная миграция - все карточки становятся 'normal'
    """
    Word = apps.get_model('words', 'Word')
    Word.objects.all().update(card_type='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_add_card_type'),
    ]

    operations = [
        migrations.RunPython(set_card_types_for_existing_words, reverse_set_card_types),
    ]
