# Generated by Django 4.2.7 on 2026-01-02 15:53

from django.db import migrations


def fix_all_card_types(apps, schema_editor):
    """
    Устанавливает правильные типы карточек для всех существующих слов:
    1. Пустые карточки (original_word начинается с '_empty_') -> 'empty'
    2. Инвертированные карточки (language == source_lang колоды) -> 'inverted'
    3. Остальные -> 'normal'
    """
    Word = apps.get_model('words', 'Word')
    Deck = apps.get_model('cards', 'Deck')
    
    # Шаг 1: Устанавливаем пустые карточки
    empty_words = Word.objects.filter(original_word__startswith='_empty_')
    empty_count = empty_words.update(card_type='empty')
    print(f"✅ Обновлено пустых карточек: {empty_count}")
    
    # Шаг 2: Находим инвертированные карточки
    # Инвертированная карточка - это слово, которое находится в колоде,
    # где language слова == source_lang колоды
    
    # Получаем все слова, которые не пустые, с предзагрузкой связей с колодами
    words_to_check = Word.objects.exclude(original_word__startswith='_empty_').prefetch_related('decks')
    
    # Собираем слова для bulk_update
    words_to_update = []
    inverted_count = 0
    normal_count = 0
    
    for word in words_to_check:
        # Проверяем, в каких колодах находится это слово
        is_inverted = False
        for deck in word.decks.all():
            # Если language слова совпадает с source_lang колоды, это инвертированная карточка
            if word.language == deck.source_lang:
                is_inverted = True
                break
        
        if is_inverted:
            word.card_type = 'inverted'
            inverted_count += 1
        else:
            # Если слово не в колодах или не инвертированное, то это нормальная карточка
            word.card_type = 'normal'
            normal_count += 1
        
        words_to_update.append(word)
    
    # Обновляем все слова одним запросом
    if words_to_update:
        Word.objects.bulk_update(words_to_update, ['card_type'], batch_size=1000)
    
    print(f"✅ Обновлено инвертированных карточек: {inverted_count}")
    print(f"✅ Обновлено обычных карточек: {normal_count}")
    print(f"📊 Итого обработано: {empty_count + inverted_count + normal_count} карточек")


def reverse_fix_all_card_types(apps, schema_editor):
    """
    Обратная миграция - все карточки становятся 'normal'
    """
    Word = apps.get_model('words', 'Word')
    Word.objects.all().update(card_type='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_set_card_types_for_existing_words'),
        ('cards', '0001_initial'),  # Нужна для доступа к модели Deck
    ]

    operations = [
        migrations.RunPython(fix_all_card_types, reverse_fix_all_card_types),
    ]
