# Generated by Django 4.2.7 on 2026-01-11 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0008_category_word_categories'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_parent',
        ),
        migrations.RemoveConstraint(
            model_name='wordrelation',
            name='unique_word_relation',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='words_categ_user_id_9f1eb2_idx',
            old_name='words_categ_user_pa_idx',
        ),
        migrations.RenameIndex(
            model_name='word',
            new_name='words_word_user_id_fe6d6e_idx',
            old_name='words_word_user_id_learning_idx',
        ),
        migrations.RenameIndex(
            model_name='wordrelation',
            new_name='words_wordr_word_fr_9f358f_idx',
            old_name='words_wordr_word_fr_idx',
        ),
        migrations.RenameIndex(
            model_name='wordrelation',
            new_name='words_wordr_word_to_647b59_idx',
            old_name='words_wordr_word_to_idx',
        ),
        migrations.AlterField(
            model_name='word',
            name='card_type',
            field=models.CharField(choices=[('normal', 'Обычная карточка'), ('inverted', 'Инвертированная карточка'), ('empty', 'Пустая карточка')], default='normal', help_text='DEPRECATED: Будет удалено после миграции на Card', max_length=10, verbose_name='Тип карточки (deprecated)'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='wordrelation',
            unique_together={('word_from', 'word_to', 'relation_type')},
        ),
    ]
