# Generated by Django 4.2.7 on 2026-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_remove_category_unique_category_name_per_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('pt', 'Португальский'), ('de', 'Немецкий'), ('es', 'Испанский'), ('fr', 'Французский'), ('it', 'Итальянский'), ('tr', 'Турецкий')], max_length=2, verbose_name='Язык'),
        ),
    ]
