# Generated by Django 4.2.7 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_alter_word_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_learning_active',
            field=models.BooleanField(default=False, help_text='True = карточки из категории попадают в общую тренировку', verbose_name='Активна для тренировки'),
        ),
    ]
