# Generated by Django 4.2.17 on 2026-03-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_category_is_learning_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='card_type',
            field=models.CharField(choices=[('normal', 'Обычная карточка'), ('inverted', 'Инвертированная карточка'), ('empty', 'Пустая карточка'), ('cloze', 'Карточка-пропуск')], default='normal', help_text='DEPRECATED: Будет удалено после миграции на Card', max_length=10, verbose_name='Тип карточки (deprecated)'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('pt', 'Portuguese'), ('de', 'German'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish')], max_length=2, verbose_name='Язык'),
        ),
    ]
